Repository ansible-collections/ansible.posix, pull requests merged in 2021-07, with the labels that each got.

#216 Fix: Resolve merge conflict - mount return backup_file(#128)
  changelogs/fragments/126_mount_not_returning_backup_file.yml
  plugins/modules/mount.py
  tests/integration/targets/mount/tasks/main.yml
Labels: feature, gate, verified

#217 Restructure integration tests for authorized_key module
  changelogs/fragments/217-restructure_authrized_key_test.yml
  tests/integration/targets/authorized_key/tasks/check_mode.yml
  tests/integration/targets/authorized_key/tasks/comments.yml
  tests/integration/targets/authorized_key/tasks/main.yml
  tests/integration/targets/authorized_key/tasks/multiple_keys.yml
  tests/integration/targets/authorized_key/tasks/setup_steps.yml
  tests/integration/targets/authorized_key/tasks/ssh_dss.yml
Labels: gate

#187 synchronize: fix to honor become_user when become_method sudo
  changelogs/fragments/187-fix-synchronize-become-user.yml
  plugins/action/synchronize.py
  tests/unit/plugins/action/fixtures/synchronize/basic_become/meta.yaml
  tests/unit/plugins/action/fixtures/synchronize/basic_become_cli/meta.yaml
Labels: gate

#213 synchronize: quotes around arguments
  changelogs/fragments/213_quote_cmd_args.yml
  plugins/modules/synchronize.py
  tests/integration/targets/synchronize/aliases
Labels: gate

#215 fix REJECT target name
  changelogs/fragments/215_fix_REJECT_target_name.yml
  plugins/modules/firewalld.py
  tests/integration/targets/firewalld/tasks/zone_target_test_cases.yml
Labels: bug, gate, verified

#214 Add new firewalld_info module to ansible.posix collection
  changelogs/fragments/214-add_firewalld_info_module.yml
  plugins/modules/firewalld_info.py
  tests/integration/targets/firewalld_info/aliases
  tests/integration/targets/firewalld_info/tasks/main.yml
  tests/integration/targets/firewalld_info/tasks/run_tests_in_started.yml
  tests/integration/targets/firewalld_info/tasks/run_tests_in_stopped.yml
Labels: gate

#229 Allow podman connections in synchronize module
  changelogs/fragments/229_add_podman_connection_plugin_to_synchronize.yml
  plugins/action/synchronize.py
Labels: gate
