Repository ansible-collections/ansible.posix, pull requests merged in 2024-10, with the labels that each got.

#387 Fix callback output to align header with roles, tasks and play RECAP
  changelogs/fragments/387_callback_output_header.yml
  plugins/callback/profile_roles.py
  plugins/callback/profile_tasks.py
  plugins/callback/timer.py
Labels: feature, verified, mergeit

#365 mount: remove boot exception if defaults in opts
  changelogs/fragments/365-boot-linux.yml
  plugins/modules/mount.py
  tests/integration/targets/mount/tasks/main.yml
Labels: mergeit

#576 Bump version info to 2.0.0 on main branch
  changelogs/fragments/576_bump_version_2.yml
  galaxy.yml
Labels: mergeit

#580 [backport][stable-1] Drop ansible-core 2.14 and set 2.15 minimum version
  changelogs/fragments/580_drop_ansible214.yml
  meta/runtime.yml
  tests/integration/targets/selinux/tasks/selinux.yml
Labels: mergeit, backport, stable-1

#581 [CI] Modify conditions for selinux integratuion tests
  changelogs/fragments/581_ci_selinux.yml
  tests/integration/targets/selinux/tasks/selinux.yml
Labels: mergeit

#583 Release 1.6.2 commit
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/580_drop_ansible214.yml
  galaxy.yml
Labels: mergeit, stable-1, release

#584 Changed the type of the forward and masquerade options from str to bool
  changelogs/fragments/584_firewalld_opt_type.yml
  plugins/modules/firewalld.py
  tests/integration/targets/firewalld/tasks/masquerade_test_cases.yml
Labels: mergeit
