Repository ansible-collections/ansible.posix, pull requests merged in 2025-07, with the labels that each got.

#650 profile_* callbacks: avoid deprecated/deleted functions
  changelogs/fragments/650-profile_tasks_roles.yml
  plugins/callback/profile_roles.py
  plugins/callback/profile_tasks.py
Labels: bug, feature, mergeit

#655 [CI][stable-1] AZP remove ansible-core devel version tests from CI matrix in stable-1
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/655_ci_remove_devel_from_stable1.yml
Labels: ci, mergeit, stable-1

#665 Update README for release of Ansible Core 2.19
  README.md
  changelogs/fragments/665_update_readme_20250728.yml
Labels: docs, mergeit

#667 [Backport][stable-2] #666
  .azure-pipelines/azure-pipelines.yml
  changelogs/fragments/666_azp_update_20250728.yml
  tests/integration/targets/firewalld/aliases
Labels: ci, mergeit, backport, stable-2

#668 [Backport][stable-2] #665
  README.md
  changelogs/fragments/665_update_readme_20250728.yml
Labels: docs, mergeit, backport, stable-2
